library(MASS)
data=read.csv("D:\\CSPROJ\\Prussian_army_horse_kick_data_1327_64.csv")
death = as.numeric(data$y)
x=fitdistr(death,'poisson')
l=x$estimate['lambda']
pmf=280*dpois(0:4,l)
plot(0:4,pmf,type='o',ylab='dpois',xlab='No. of deaths',ylim=c(0,150),col='Red')
table(data.frame(0:4,280*dpois(death,l)))
barplot(table(death),0:4,width=1,space=0,ylim=c(0,160),xlab='No. of Deaths',ylab='Rel. Frequency')
lines(0:4,pmf,type='o',ylab='dpois',xlab='No. of deaths',ylim=c(0,150),col='red')
legend('topright',legend=c('PMF'),col='red',lty=5)
